# Generated by Django 5.1.4 on 2024-12-27 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_setup', '0002_bocabocasetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bocabocasetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m'),
        ),
        migrations.AddField(
            model_name='menulink',
            name='bocaboca_setup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bocaboca_setup.bocabocasetup'),
        ),
    ]
