# Generated by Django 5.1.4 on 2025-01-06 14:46

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_setup', '0003_bocabocasetup_favicon_menulink_bocaboca_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bocabocasetup',
            name='span_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bocabocasetup',
            name='span_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bocabocasetup',
            name='span_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bocabocasetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m', validators=[utils.model_validators.validate_png]),
        ),
    ]
