# Generated by Django 5.1.4 on 2025-04-03 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocabocaApp', '0005_client'),
        ('bocaboca_profile', '0025_customuser_review_delete_interestarea_and_more'),
        ('bocaboca_setup', '0004_bocabocasetup_span_1_bocabocasetup_span_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocaboca_profile.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocabocaApp.client')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocaboca_profile.newuser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocaboca_setup.service')),
            ],
        ),
    ]
