version: "3.9"

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
      # dockerfile: Dockerfile   # (opcional, se o nome for diferente)
    environment:
      - PORT=8000            # <— PORT agora no serviço certo
      # - DEBUG=true         # (opcional, se quiser rodar em DEV)
    env_file:
      - ./dotenv_files/.env  # POSTGRES_* etc.
    ports:
      - "8000:8000"
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    depends_on:
      - psql
    # Se der permissão em volumes no Linux, pode usar:
    # user: "1000:1000"

  psql:
    container_name: psql
    image: postgres:13-alpine
    env_file:
      - ./dotenv_files/.env   # POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - psql
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
