# Generated by Django 3.2.25 on 2025-04-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='iBnS01ykp8hMJaVfwwzg39uLZuoytcH2XnhSukPwjfPNirwbOzuZNhfsNiSChbXJ', max_length=64, unique=True),
        ),
    ]
