# Generated by Django 3.2.25 on 2025-08-08 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone',
            field=models.CharField(db_index=True, default=9990000, max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Telefone inválido.')]),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='aGTBL7WyXuoN2OvS3yuy81nGS7idURYHvr99EuUQdhTlyLnSRn9PojZWY1cgF8vK', max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='newuser',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('phone',), name='uniq_newuser_phone_not_null'),
        ),
    ]
