# Generated by Django 5.1.4 on 2025-01-10 21:52

import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0003_pendinguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=64, unique=True),
        ),
    ]
