# Generated by Django 3.2.25 on 2025-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0003_auto_20250808_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='DwitmymKu0ehH1vvOIhS50tNg90YDAMdAHLaNEmQO9niTUSFXLYn3AJpZc4vL5g6', max_length=64, unique=True),
        ),
    ]
