# Generated by Django 3.2.25 on 2025-08-08 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0004_alter_pendinguser_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='newuser',
            name='uniq_newuser_phone_not_null',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Telefone inválido.')]),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='Pu2H9qzd0A1YM4Ak3snKcHBQN5RqRBlaDrU8FkKoxD2CYlWZ9w3IuV6CJqx7NCGH', max_length=64, unique=True),
        ),
    ]
