# Generated by Django 5.1.4 on 2025-01-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0005_remove_pendinguser_email_remove_pendinguser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='07uDKnLJ3jAk9jKrXq5axg9AKGHlNZwvsUwGx3kOjgx5i67zPtZcIF1A5CZyQl8H', max_length=64, unique=True),
        ),
    ]
