# Generated by Django 3.2.25 on 2025-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0005_auto_20250808_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='yq3K8FjD05NDDOJwDfKZHbsy2KLNDhmjyE8joEpFmAXqiy0N3Pkx8kvAOzMH4I2x', max_length=64, unique=True),
        ),
    ]
