# Generated by Django 5.1.4 on 2025-01-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0006_alter_pendinguser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='iwLUXWu3CBvfyBZnYpx1Wuwt8UjLLsBykJZwMJ6mXZncPyG1JrPfF28AascNklNS', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
