# Generated by Django 3.2.25 on 2025-08-12 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0007_cleanup_phone_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Telefone inválido.')]),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='0MmlDQYgjInjm0MQBebwOpFokBlgEdImOy8AIZrqldh1NCwO1szBBRdnbF8TOmg2', max_length=64, unique=True),
        ),
    ]
