# Generated by Django 5.1.4 on 2025-01-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0008_alter_pendinguser_token_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='YHQbyT7wtxIcRk15JYc2AcJJgmfusJNUh0dn8HJlWwTSjb69ISQ6MKIAD1Q84JUX', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
