# Generated by Django 5.1.4 on 2025-01-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0009_alter_pendinguser_token_alter_profile_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='5cAictO1GhGehWBnEOkgJTDsMTxtLSdTOcTQlToKJ3S6GEnZxbkDIvI9RL82kWPj', max_length=64, unique=True),
        ),
    ]
