# Generated by Django 5.1.4 on 2025-01-11 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0010_alter_pendinguser_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='ErnZvKrjiyNB7EGxxP7BnXJsgRgPRzs1sTUWFPkx0rGP8Kd4hClRQ3OoAiG1gwfm', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('professional_title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('professional_experience', models.TextField()),
                ('interest_areas', models.CharField(max_length=255)),
                ('ability', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
