# Generated by Django 5.1.4 on 2025-01-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0012_alter_pendinguser_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='interest_areas',
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='nz4nPhmEvtRrlEoSh2CtRjZ0jkB21QEcjjd4jD8YwRI4K1z3QDJKvvdxg3CkG3eb', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='interest_areas',
            field=models.ManyToManyField(blank=True, to='bocaboca_profile.interestarea'),
        ),
    ]
