# Generated by Django 5.1.4 on 2025-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0013_interestarea_remove_newuser_interest_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='StNNkZbNIGHbymjhreYJSIqVgVuQy9Onop3C9dFdlZX2Gpc0Gllcozw60CvUBhl2', max_length=64, unique=True),
        ),
    ]
