# Generated by Django 5.1.4 on 2025-01-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0014_alter_pendinguser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='pv0T6dB4YLtdAIJLFw3EfjNQiPcLEuO4EuqvvyleQg66RiTNAhMLfymwuM6h2PGq', max_length=64, unique=True),
        ),
    ]
