# Generated by Django 5.1.4 on 2025-01-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0015_alter_pendinguser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='Jeq1wfkBHDOsf0ygxVALd2nKF7miRAcQAvlyHpQxRL5v2EkLwJeyMZFY5Mlhwikk', max_length=64, unique=True),
        ),
    ]
