# Generated by Django 5.1.4 on 2025-01-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0020_interestarea_label1_alter_pendinguser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestarea',
            name='label1',
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='VQHKuIRsKk06tABgXCN8vsAEk6k05ETdTt9nfQzHnfmYIoHjehwsiRwg96fqhcSE', max_length=64, unique=True),
        ),
    ]
