# Generated by Django 5.1.4 on 2025-01-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0021_remove_interestarea_label1_alter_pendinguser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='3uM4C7sKqFRV2il4v8LVNuU7GsreDC8UlSDIgOgFWZVIxuRPe8n1FDlKHsOpJNRM', max_length=64, unique=True),
        ),
    ]
