# Generated by Django 5.1.4 on 2025-01-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0022_alter_pendinguser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='interest_areas',
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.CharField(default='zchbNoBOaaKgN0oaOI6IXj5yo3agW57e0gdzVxLsB1KyEvZ4OADL3WDFz8fMGKEr', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='interest_areas',
            field=models.TextField(blank=True),
        ),
    ]
