# Generated by Django 5.1.4 on 2025-04-03 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocaboca_profile', '0025_customuser_review_delete_interestarea_and_more'),
        ('bocaboca_setup', '0005_service_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bocaboca_setup.service'),
        ),
    ]
