# Generated by Django 3.2.25 on 2025-08-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bocaboca_profile', '0001_initial'),
        ('bocabocaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bocaboca_profile.customuser'),
        ),
    ]
