# Generated by Django 5.1.4 on 2025-01-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocabocaApp', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('professional_title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('professional_experience', models.TextField()),
                ('ability', models.TextField()),
                ('interest_areas', models.ManyToManyField(to='bocabocaApp.interestarea')),
            ],
        ),
    ]
