# Generated by Django 5.1.4 on 2025-01-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bocabocaApp', '0003_interestarea_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interest_areas',
        ),
        migrations.DeleteModel(
            name='InterestArea',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
