# Generated by Django 5.1.4 on 2025-04-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocabocaApp', '0004_remove_profile_interest_areas_delete_interestarea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('preferred_service', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
